// Generated by build-dist.js on every build — don't edit by hand.
// Server-rendered pages use these to link the same content-hashed URLs the
// static pages get, so a deploy never leaves them on a stale stylesheet.
export const ASSET_VERSIONS = {
  '/styles.css': '8a3a1a98',
  '/client.js': 'b5bd20e1',
  '/listing-actions.js': '8a34b3cf',
  '/profile-actions.js': '26b547c1',
};
